name: anxeb_flutter
description: Highly scalable mobile Flutter cross-platform library
publish_to: 'none'
version: 2.2.0
homepage: https://github.com/nodrix/anxeb-flutter

environment:
  sdk: ">=2.7.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_middleware:
    path: plugins/android_middleware
  cupertino_icons: ^1.0.5
  flutter_keyboard_visibility: ^5.4.0
  fluttericon: ^2.0.0
  community_material_icon: ^5.9.55
  ionicons: ^0.2.1
  camera: ^0.10.0+4
  image_crop: ^0.4.1
  path: ^1.8.1
  path_provider: ^2.0.11
  ai_barcode: ^3.2.4
  barcode_scan2: ^4.2.1
  dio: ^5.2.0+1
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh_flutter3: ^2.0.1
  google_sign_in: ^5.4.2
  oauth1: ^2.0.0
  flutter_facebook_auth: ^4.4.1+1
  device_info: ^2.0.3
  percent_indicator: ^4.2.2
  another_flushbar: ^1.12.29
  mime: ^1.0.3
  qr_flutter: 4.0.0
  photo_view: ^0.14.0
  credit_card_validator: ^2.1.0
  file_picker: ^5.2.3
  sign_in_with_apple: ^4.2.0
  firebase_core: ^2.6.0
  firebase_messaging: ^14.2.3
  firebase_analytics: ^10.1.2
  flutter_app_badger: ^1.5.0
  url_launcher: ^6.1.7
  flutter_pdfview: ^1.2.9
  share: ^2.0.4
  flutter_translate: ^4.0.3
  permission_handler: ^10.2.0
  app_settings: 4.1.8
  package_info_plus: ^3.0.2
  in_app_review: ^2.0.6
  easy_mask: ^2.0.1
  bluetooth_print: ^4.3.0
  smooth_page_indicator: ^1.0.1
  open_store: ^0.5.0
  scan: ^1.6.0
  go_router: ^6.0.6
  dotted_line: ^3.1.0
  google_maps_flutter_web: ^0.4.0+9
  google_maps_flutter: ^2.2.5
  google_geocoding_api: ^1.2.0
  just_the_tooltip: ^0.0.12
  pointer_interceptor: ^0.9.3+4

flutter:
  uses-material-design: true